[package]
name = "cardcraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cardcraft"
path = "src/lib.rs"

[[bin]]
name = "cardcraft-cli"
path = "src/cli.rs"
